// Auth actions
export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';
export const AUTH_LOGOUT_REQUEST = 'AUTH_LOGOUT_REQUEST';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_FAILURE = 'AUTH_LOGOUT_FAILURE';
export const AUTH_GET_PROFILE_DATA_REQUEST = 'AUTH_GET_PROFILE_DATA_REQUEST';
export const AUTH_GET_PROFILE_DATA_SUCCESS = 'AUTH_GET_PROFILE_DATA_SUCCESS';
export const AUTH_GET_PROFILE_DATA_FAILURE = 'AUTH_GET_PROFILE_DATA_FAILURE';